name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Build kernel via HF Jobs
        uses: huggingface/kernel-builder-job@main
        with:
          token: ${{ secrets.HF_TOKEN }}
          namespace: drbh
          # image: uses default nix image
          script: |
            kernel-builder init --name drbh/test-kernel --backends cuda
            cd test-kernel
            git init && git add -A && git commit -m init
            kernel-builder build
